#!/usr/bin/env bash
# Regenerates kulmi_setup.sql from migrations/ in the correct order.
# Usage: bash scripts/build-setup.sh
set -e
cd "$(dirname "$0")/.."
FILES="migration.sql migration_sessions.sql migration_storage.sql"
for i in $(seq 2 99); do
  [ -f "migrations/migration_v$i.sql" ] && FILES="$FILES migration_v$i.sql"
done
{
  echo "-- KULMI combined setup — generated by scripts/build-setup.sh. Run in Supabase SQL editor. Safe to re-run."
  for f in $FILES; do
    echo ""; echo "-- >>> $f"; cat "migrations/$f"; echo ""
  done
} > kulmi_setup.sql
wc -l kulmi_setup.sql
